runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "submissiondicoding99.appspot.com"

handlers:
  - url: /
    static_dir: index.html

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
